version: '3.3'
services:
  pwlessdb:
    image: postgres:13
    ports:
      - 127.0.0.1:5432:5432
    volumes:
      - ./postgres/init/:/docker-entrypoint-initdb.d/
    environment:
      POSTGRES_DB: pwless
      POSTGRES_MULTIPLE_DATABASES: pwless_test
      POSTGRES_USER: pwless
      POSTGRES_PASSWORD: pwless
      PGDATA: /var/lib/postgresql/data/pwless

# Names our volume
volumes:
  pwless-db: